### ISSUE TITLE
添加apollo-client到项目中启动出现警告

### ISSUE THREAD

**Issue by liuyukuai** [ctripcorp/apollo#2427] opened 2019-07-07 07:33 UTC
apollo版本1.4.0
spring-boot版本: 2.1.6

2019-07-07 15:28:41.497  WARN 38486 --- [           main] o.s.b.c.p.PropertySourcesDeducer         : Multiple PropertySourcesPlaceholderConfigurer beans registered [propertySourcesPlaceholderConfigurer, org.springframework.context.support.PropertySourcesPlaceholderConfigurer], falling back to Environment

**Comment by nobodyiam** [comment] 2019-07-07 09:43
see #2328

**Comment by kezhenxu94** [comment] 2019-07-18 00:38
Duplicate of #2328

**Closed by kezhenxu94** 2019-07-18 00:38 UTC
